name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Chạy khi push vào nhánh main

jobs:
  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest  # Dùng Ubuntu để tránh lỗi và build nhanh hơn
    strategy:
      matrix:
        node-version: [20]  # Bạn có thể dùng thêm 22 nếu thực sự cần

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
